# Deployment Config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-mysql-deployment
  namespace: devops-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-mysql-deployment
  template:
    metadata:
      labels:
        app: wordpress-mysql-deployment
    spec:
      serviceAccountName: jenkins-admin
      securityContext:
            fsGroup: 1000
            runAsUser: 1000
      volumes:
            - name: jenkins-data
              persistentVolumeClaim:
                claimName: jenkins-pv-claim
      containers:
        - name: wordpress-container
          image: wordpress:php8.1-fpm
          env:
          - name: WORDPRESS_DB_HOST
            value: "db"
          - name: WORDPRESS_DB_USER
            value: "exampleuser"
          - name: WORDPRESS_DB_PASSWORD
            value: "examplepass"
          - name: WORDPRESS_DB_NAME
            value: "exampledb"
          ports:
            - name: wordport
              containerPort: 8081
#          livenessProbe:
#            httpGet:
#              path: "/login"
#              port: 8081
#            initialDelaySeconds: 600
#            periodSeconds: 60
#            timeoutSeconds: 60
#            failureThreshold: 5
#          readinessProbe:
#            httpGet:
#              path: "/login"
#              port: 8081
#            initialDelaySeconds: 360
#            periodSeconds: 60
#            timeoutSeconds: 60
#            failureThreshold: 3
          volumeMounts:
            - mountPath: /var/www/html
              name: jenkins-data
        - name: php-fpm
          image: otezvikentiy/php7.2-fpm:0.0.12
          volumeMounts:
            - mountPath: /var/lib/php7.2-fpm
              name: jenkins-data
        - name: mysql-container
          image: mysql:5.7
          env:
          - name: MYSQL_DATABASE
            value: "exampledb"
          - name: MYSQL_USER
            value: "exampleuser"
          - name: MYSQL_PASSWORD
            value: "examplepass"
          - name: MYSQL_RANDOM_ROOT_PASSWORD
            value: "1"
          ports:
            - name: mysqlport
              containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: jenkins-data
# Service Config
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  namespace: devops-tools
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8081'
spec:
  selector: 
    app: wordpress-mysql-deployment
  type: NodePort  
  ports:
    - name: wordport
      port: 8081
      targetPort: 8081
      nodePort: 32001
    - name: jnlp-port
      port: 50001
      targetPort: 50001
    - name: mysqlport
      port: 3306
      targetPort: 3306
      nodePort: 32002
