# Deployment Config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  namespace: devops-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-deployment
  template:
    metadata:
      labels:
        app: wordpress-deployment
    spec:
      serviceAccountName: jenkins-admin
      securityContext:
            fsGroup: 1000
            runAsUser: 1000
      volumes:
            - name: jenkins-data
              persistentVolumeClaim:
                claimName: jenkins-pv-claim
      containers:
        - name: wordpress-container
          image: wordpress:php8.1-fpm-alpine
          env:
          - name: WORDPRESS_DB_HOST
            value: "db"
          - name: WORDPRESS_DB_USER
            value: "exampleuser"
          - name: WORDPRESS_DB_PASSWORD
            value: "examplepass"
          - name: WORDPRESS_DB_NAME
            value: "exampledb"
          ports:
            - name: wordport
              containerPort: 80
#          livenessProbe:
#            httpGet:
#              path: "/login"
#              port: 8081
#            initialDelaySeconds: 600
#            periodSeconds: 60
#            timeoutSeconds: 60
#            failureThreshold: 5
#          readinessProbe:
#            httpGet:
#              path: "/login"
#              port: 8081
#            initialDelaySeconds: 360
#            periodSeconds: 60
#            timeoutSeconds: 60
#            failureThreshold: 3
          volumeMounts:
            - mountPath: /var/www/html
              name: jenkins-data
# Service Config
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  namespace: devops-tools
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '80'
spec:
  selector: 
    app: wordpress-deployment
  type: NodePort  
  ports:
    - name: wordport
      port: 8081
      targetPort: 80
      nodePort: 32001
