apiVersion: v1
kind: Service
metadata:
  name: php-fpm
  namespace: devops-tools
  labels:
    tier: backend
spec:
  selector:
    app: php
    tier: backend
  ports:
  - protocol: TCP
    port: 3306
